### ISSUE TITLE
assemble할 때 리스트에 만약 알파벳이 있을 경우, 이상한 글자가 만들어져요

### ISSUE THREAD

**Issue by kimkevin** [kimkevin/HangulParser#1]
list.add("ㄱ");
list.add("ㅣ");
list.add("a");
list.add("ㅁ");

HangulParser.getInstance().assemble(list)

result : 긯

**Comment by sinhwa2k** [comment]
I changed assemble method.
Please review the Pull request.

**Comment by kimkevin** [comment]
I put the comments on your codes. please check it out.

**Comment by sinhwa2k** [comment]
I applied java convention. please review it.
